# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Facebook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Facebook

  target 'FacebookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FacebookUITests' do
    # Pods for testing
  end

	pod 'SwiftyJSON', '~> 4.0'
	pod 'ObjectMapper', '~> 3.4'
	pod 'AlamofireImage', '~> 4.1'

end
